name: First workflow
on: [push]
jobs:
  first_job:
    runs-on: self-hosted
    steps:
      - name: print greeting
        run: echo "Hello world"
      - name: print good bye
        run: echo "good bye"
